### ISSUE TITLE
Need someone to take over maintenance of UE4 plugin

### ISSUE THREAD

**Issue by jonathanpotts** [jonathanpotts/Spectral#4]
I am looking for a volunteer to take over maintenance of the UE4 plugin (mainly updating it to work with new engine versions). Thanks.

**Comment by JasonBucotte** [comment]
Hi! Actually just found the project, will take a look at it today as I've wanted to add Logi control from within game for a while. Has there been any progress off GitHub since this post?
edit: currently seems to work as intended, though I need to get old LGS installed instead of GHUB for the virtual devices and I'll keep testing!

**Comment by jonathanpotts** [comment]
The code is up-to-date in the repo. The main issue would be making updates if needed for new UE4 versions. The plugin used to be on the UE4 marketplace but the maintenance added too much overhead for me to keep it on there.
